package com.fmall.pojo;
// Generated 2017-6-12 9:32:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private int id;
     private Fuser fuser;
     private Product product;
     private Integer quantity;
     private Date createTime;
     private Date updateTime;

    public Cart() {
    }

	
    public Cart(int id, Fuser fuser, Product product) {
        this.id = id;
        this.fuser = fuser;
        this.product = product;
    }
    public Cart(int id, Fuser fuser, Product product, Integer quantity, Date createTime, Date updateTime) {
       this.id = id;
       this.fuser = fuser;
       this.product = product;
       this.quantity = quantity;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Fuser getFuser() {
        return this.fuser;
    }
    
    public void setFuser(Fuser fuser) {
        this.fuser = fuser;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


