package com.fmall.pojo;
// Generated 2017-6-12 9:32:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categeory generated by hbm2java
 */
public class Categeory  implements java.io.Serializable {


     private int id;
     private Categeory categeory;
     private String categeoryName;
     private Date createTime;
     private Date updateTime;
     private Set categeories = new HashSet(0);

    public Categeory() {
    }

	
    public Categeory(int id, String categeoryName) {
        this.id = id;
        this.categeoryName = categeoryName;
    }
    public Categeory(int id, Categeory categeory, String categeoryName, Date createTime, Date updateTime, Set categeories) {
       this.id = id;
       this.categeory = categeory;
       this.categeoryName = categeoryName;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.categeories = categeories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categeory getCategeory() {
        return this.categeory;
    }
    
    public void setCategeory(Categeory categeory) {
        this.categeory = categeory;
    }
    public String getCategeoryName() {
        return this.categeoryName;
    }
    
    public void setCategeoryName(String categeoryName) {
        this.categeoryName = categeoryName;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Set getCategeories() {
        return this.categeories;
    }
    
    public void setCategeories(Set categeories) {
        this.categeories = categeories;
    }




}


