package com.fmall.pojo;
// Generated 2017-6-12 9:32:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Forder generated by hbm2java
 */
public class Forder  implements java.io.Serializable {


     private String orderId;
     private Fuser fuser;
     private String oaddress;
     private Date sendTime;
     private Date endDate;
     private int postage;
     private int orderStatus;
     private Date createTime;
     private Date updateTime;
     private Set orderItems = new HashSet(0);

    public Forder() {
    }

	
    public Forder(String orderId, String oaddress, int postage, int orderStatus) {
        this.orderId = orderId;
        this.oaddress = oaddress;
        this.postage = postage;
        this.orderStatus = orderStatus;
    }
    public Forder(String orderId, Fuser fuser, String oaddress, Date sendTime, Date endDate, int postage, int orderStatus, Date createTime, Date updateTime, Set orderItems) {
       this.orderId = orderId;
       this.fuser = fuser;
       this.oaddress = oaddress;
       this.sendTime = sendTime;
       this.endDate = endDate;
       this.postage = postage;
       this.orderStatus = orderStatus;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.orderItems = orderItems;
    }
   
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
    public Fuser getFuser() {
        return this.fuser;
    }
    
    public void setFuser(Fuser fuser) {
        this.fuser = fuser;
    }
    public String getOaddress() {
        return this.oaddress;
    }
    
    public void setOaddress(String oaddress) {
        this.oaddress = oaddress;
    }
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public int getPostage() {
        return this.postage;
    }
    
    public void setPostage(int postage) {
        this.postage = postage;
    }
    public int getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(int orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Set getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set orderItems) {
        this.orderItems = orderItems;
    }




}


