package com.fmall.pojo;
// Generated 2017-6-12 9:32:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fuser generated by hbm2java
 */
public class Fuser  implements java.io.Serializable {


     private String fuid;
     private String nickname;
     private String password;
     private String phone;
     private String image;
     private int urole;
     private String question;
     private String answer;
     private Date createTime;
     private Date updateTime;
     private Set forders = new HashSet(0);
     private Set carts = new HashSet(0);

    public Fuser() {
    }

	
    public Fuser(String fuid,String password, int urole) {
        this.fuid = fuid;
        this.password = password;
        this.urole = urole;
    }
    public Fuser(String fuid, String nickname, String password, String phone, String image, int urole, String question, String answer, Date createTime, Date updateTime, Set forders, Set carts) {
       this.fuid = fuid;
       this.nickname = nickname;
       this.password = password;
       this.phone = phone;
       this.image = image;
       this.urole = urole;
       this.question = question;
       this.answer = answer;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.forders = forders;
       this.carts = carts;
    }
   
    public String getFuid() {
        return this.fuid;
    }
    
    public void setFuid(String fuid) {
        this.fuid = fuid;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public int getUrole() {
        return this.urole;
    }
    
    public void setUrole(int urole) {
        this.urole = urole;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Set getForders() {
        return this.forders;
    }
    
    public void setForders(Set forders) {
        this.forders = forders;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }




}


