package com.fmall.pojo;
// Generated 2017-6-12 9:32:51 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * OrderItem generated by hbm2java
 */
public class OrderItem  implements java.io.Serializable {


     private int id;
     private Forder forder;
     private Product product;
     private String productImage;
     private String productName;
     private BigDecimal currentPrice;
     private Integer quantity;
     private BigDecimal totalPrice;
     private Date createTime;
     private Date updateTime;

    public OrderItem() {
    }

	
    public OrderItem(int id, Forder forder, Product product, BigDecimal currentPrice, BigDecimal totalPrice) {
        this.id = id;
        this.forder = forder;
        this.product = product;
        this.currentPrice = currentPrice;
        this.totalPrice = totalPrice;
    }
    public OrderItem(int id, Forder forder, Product product, String productImage, String productName, BigDecimal currentPrice, Integer quantity, BigDecimal totalPrice, Date createTime, Date updateTime) {
       this.id = id;
       this.forder = forder;
       this.product = product;
       this.productImage = productImage;
       this.productName = productName;
       this.currentPrice = currentPrice;
       this.quantity = quantity;
       this.totalPrice = totalPrice;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Forder getForder() {
        return this.forder;
    }
    
    public void setForder(Forder forder) {
        this.forder = forder;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getCurrentPrice() {
        return this.currentPrice;
    }
    
    public void setCurrentPrice(BigDecimal currentPrice) {
        this.currentPrice = currentPrice;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


