package com.fmall.pojo;
// Generated 2017-6-12 9:32:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int pid;
     private String name;
     private String subTitle;
     private BigDecimal price;
     private Integer stock;
     private Integer sales;
     private Integer categoryId;
     private String mainImage;
     private String subImages;
     private Integer pstatus;
     private String detail;
     private Date createTime;
     private Date updateTime;
     private Set promotionStrategyItems = new HashSet(0);
     private Set carts = new HashSet(0);
     private Set orderItems = new HashSet(0);

    public Product() {
    }

	
    public Product(int pid, String name, BigDecimal price) {
        this.pid = pid;
        this.name = name;
        this.price = price;
    }
    public Product(int pid, String name, String subTitle, BigDecimal price, Integer stock, Integer sales, Integer categoryId, String mainImage, String subImages, Integer pstatus, String detail, Date createTime, Date updateTime, Set promotionStrategyItems, Set carts, Set orderItems) {
       this.pid = pid;
       this.name = name;
       this.subTitle = subTitle;
       this.price = price;
       this.stock = stock;
       this.sales = sales;
       this.categoryId = categoryId;
       this.mainImage = mainImage;
       this.subImages = subImages;
       this.pstatus = pstatus;
       this.detail = detail;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.promotionStrategyItems = promotionStrategyItems;
       this.carts = carts;
       this.orderItems = orderItems;
    }
   
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSubTitle() {
        return this.subTitle;
    }
    
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Integer getSales() {
        return this.sales;
    }
    
    public void setSales(Integer sales) {
        this.sales = sales;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getMainImage() {
        return this.mainImage;
    }
    
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage;
    }
    public String getSubImages() {
        return this.subImages;
    }
    
    public void setSubImages(String subImages) {
        this.subImages = subImages;
    }
    public Integer getPstatus() {
        return this.pstatus;
    }
    
    public void setPstatus(Integer pstatus) {
        this.pstatus = pstatus;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Set getPromotionStrategyItems() {
        return this.promotionStrategyItems;
    }
    
    public void setPromotionStrategyItems(Set promotionStrategyItems) {
        this.promotionStrategyItems = promotionStrategyItems;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set orderItems) {
        this.orderItems = orderItems;
    }




}


