package com.fmall.pojo;
// Generated 2017-6-12 9:32:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PromotionStrategy generated by hbm2java
 */
public class PromotionStrategy  implements java.io.Serializable {


     private int id;
     private String promotionId;
     private Date startDate;
     private Date endDate;
     private double discount;
     private String title;
     private Date createTime;
     private Date updateTime;
     private Set promotionStrategyItems = new HashSet(0);

    public PromotionStrategy() {
    }

	
    public PromotionStrategy(int id, Date startDate, Date endDate, double discount) {
        this.id = id;
        this.startDate = startDate;
        this.endDate = endDate;
        this.discount = discount;
    }
    public PromotionStrategy(int id, String promotionId, Date startDate, Date endDate, double discount, String title, Date createTime, Date updateTime, Set promotionStrategyItems) {
       this.id = id;
       this.promotionId = promotionId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.discount = discount;
       this.title = title;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.promotionStrategyItems = promotionStrategyItems;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPromotionId() {
        return this.promotionId;
    }
    
    public void setPromotionId(String promotionId) {
        this.promotionId = promotionId;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Set getPromotionStrategyItems() {
        return this.promotionStrategyItems;
    }
    
    public void setPromotionStrategyItems(Set promotionStrategyItems) {
        this.promotionStrategyItems = promotionStrategyItems;
    }




}


