package com.fmall.pojo;
// Generated 2017-6-12 9:32:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PromotionStrategyItem generated by hbm2java
 */
public class PromotionStrategyItem  implements java.io.Serializable {


     private int id;
     private Product product;
     private PromotionStrategy promotionStrategy;
     private Date createTime;
     private Date updateTime;

    public PromotionStrategyItem() {
    }

	
    public PromotionStrategyItem(int id, Product product) {
        this.id = id;
        this.product = product;
    }
    public PromotionStrategyItem(int id, Product product, PromotionStrategy promotionStrategy, Date createTime, Date updateTime) {
       this.id = id;
       this.product = product;
       this.promotionStrategy = promotionStrategy;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public PromotionStrategy getPromotionStrategy() {
        return this.promotionStrategy;
    }
    
    public void setPromotionStrategy(PromotionStrategy promotionStrategy) {
        this.promotionStrategy = promotionStrategy;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


